// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB247IojWAFCJ92VJEjudfNcQf9Hr22NS4',
    appId: '1:346476230837:web:3b1ae754bba797a3ade6fc',
    messagingSenderId: '346476230837',
    projectId: 'flutter-prep-6a4d9',
    authDomain: 'flutter-prep-6a4d9.firebaseapp.com',
    databaseURL: 'https://flutter-prep-6a4d9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6a4d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHR_FpoDGWZLEhrilEckeVMQGSyRq6X0',
    appId: '1:346476230837:android:d27c3b96fefec092ade6fc',
    messagingSenderId: '346476230837',
    projectId: 'flutter-prep-6a4d9',
    databaseURL: 'https://flutter-prep-6a4d9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6a4d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJas1VzepjeFAzwnbI6iEb1n9eWLt0mc',
    appId: '1:346476230837:ios:db883c9c521c4183ade6fc',
    messagingSenderId: '346476230837',
    projectId: 'flutter-prep-6a4d9',
    databaseURL: 'https://flutter-prep-6a4d9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6a4d9.appspot.com',
    iosBundleId: 'com.example.sapienza1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJas1VzepjeFAzwnbI6iEb1n9eWLt0mc',
    appId: '1:346476230837:ios:db883c9c521c4183ade6fc',
    messagingSenderId: '346476230837',
    projectId: 'flutter-prep-6a4d9',
    databaseURL: 'https://flutter-prep-6a4d9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6a4d9.appspot.com',
    iosBundleId: 'com.example.sapienza1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsdYK6lSwtUZfDTwwtlisxMT_qYIqFwhE',
    appId: '1:346476230837:web:f65e8c0908bbecd3ade6fc',
    messagingSenderId: '346476230837',
    projectId: 'flutter-prep-6a4d9',
    authDomain: 'flutter-prep-6a4d9.firebaseapp.com',
    databaseURL: 'https://flutter-prep-6a4d9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6a4d9.appspot.com',
    measurementId: 'G-QZH9T428FM',
  );
}
